# Generated by Django 6.0 on 2026-01-13 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('DOG', '강아지'), ('CAT', '고양이'), ('OTHER', '기타')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', '수컷'), ('F', '암컷')], max_length=1)),
                ('birth', models.DateField(blank=True, null=True)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('is_neutered', models.BooleanField(default=False)),
                ('allergy', models.JSONField(blank=True, null=True)),
                ('etc', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_pet_name_per_user')],
            },
        ),
    ]
