# Generated by Django 6.0 on 2026-01-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_id", models.IntegerField()),
                ("drug_name", models.CharField(max_length=100)),
                ("dose_amount", models.FloatField()),
                ("dose_unit", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("memo", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DrugSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency_type", models.CharField(max_length=50)),
                ("interval_n", models.IntegerField(default=1)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="drug.drugplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_of_day", models.TimeField()),
                ("seq", models.IntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="times",
                        to="drug.drugschedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_at", models.DateTimeField()),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drug.drugplan"
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drug.drugtime",
                    ),
                ),
            ],
        ),
    ]
