# Generated by Django 6.0 on 2026-01-18 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drug", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drugtime",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="drugplan",
            name="pet_id",
        ),
        migrations.AddField(
            model_name="drugplan",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "매일"),
                    ("EOD", "격일"),
                    ("WEEKLY", "주 N회"),
                    ("CUSTOM", "사용자 지정"),
                ],
                default="DAILY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="drugplan",
            name="pet_name",
            field=models.CharField(
                default="강아지", max_length=50, verbose_name="반려동물 이름"
            ),
        ),
        migrations.AddField(
            model_name="drugtime",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="times",
                to="drug.drugplan",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DrugSchedule",
        ),
    ]
