# Generated by Django 6.0 on 2026-01-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drug", "0002_remove_drugtime_schedule_remove_drugplan_pet_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drugplan",
            name="dose_amount",
        ),
        migrations.RemoveField(
            model_name="drugplan",
            name="dose_unit",
        ),
        migrations.RemoveField(
            model_name="drugrecord",
            name="status",
        ),
        migrations.RemoveField(
            model_name="drugrecord",
            name="time",
        ),
        migrations.AddField(
            model_name="drugplan",
            name="dosage",
            field=models.CharField(default=1, max_length=50, verbose_name="용량/단위"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drugrecord",
            name="is_taken",
            field=models.BooleanField(default=False, verbose_name="복용 여부"),
        ),
        migrations.AlterField(
            model_name="drugplan",
            name="drug_name",
            field=models.CharField(max_length=100, verbose_name="약 이름"),
        ),
        migrations.AlterField(
            model_name="drugplan",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="종료일"),
        ),
        migrations.AlterField(
            model_name="drugplan",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "매일"),
                    ("EOD", "격일"),
                    ("WEEKLY", "주 N회"),
                    ("CUSTOM", "사용자 지정"),
                ],
                default="DAILY",
                max_length=20,
                verbose_name="복용 주기",
            ),
        ),
        migrations.AlterField(
            model_name="drugplan",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성 계획"),
        ),
        migrations.AlterField(
            model_name="drugplan",
            name="memo",
            field=models.TextField(blank=True, null=True, verbose_name="메모"),
        ),
        migrations.AlterField(
            model_name="drugplan",
            name="pet_name",
            field=models.CharField(max_length=50, verbose_name="반려동물 이름"),
        ),
        migrations.AlterField(
            model_name="drugplan",
            name="start_date",
            field=models.DateField(verbose_name="시작일"),
        ),
        migrations.AlterField(
            model_name="drugrecord",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="drug.drugplan",
            ),
        ),
        migrations.AlterField(
            model_name="drugrecord",
            name="schedule_at",
            field=models.DateTimeField(verbose_name="예정 일시"),
        ),
        migrations.AlterField(
            model_name="drugrecord",
            name="taken_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="실제 복용 시각"
            ),
        ),
        migrations.AlterField(
            model_name="drugtime",
            name="seq",
            field=models.IntegerField(default=1, verbose_name="복용 순번"),
        ),
        migrations.AlterField(
            model_name="drugtime",
            name="time_of_day",
            field=models.TimeField(verbose_name="복용 시간"),
        ),
    ]
